
package mypackage;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws.enset.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param mantant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Convert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Convert", targetNamespace = "http://ws.enset.ma/", className = "mypackage.Convert")
    @ResponseWrapper(localName = "ConvertResponse", targetNamespace = "http://ws.enset.ma/", className = "mypackage.ConvertResponse")
    @Action(input = "http://ws.enset.ma/BanqueService/ConvertRequest", output = "http://ws.enset.ma/BanqueService/ConvertResponse")
    public double convert(
        @WebParam(name = "mantant", targetNamespace = "")
        double mantant);

    /**
     * 
     * @param code
     * @return
     *     returns mypackage.Compte
     */
    @WebMethod(operationName = "GetCompte")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetCompte", targetNamespace = "http://ws.enset.ma/", className = "mypackage.GetCompte")
    @ResponseWrapper(localName = "GetCompteResponse", targetNamespace = "http://ws.enset.ma/", className = "mypackage.GetCompteResponse")
    @Action(input = "http://ws.enset.ma/BanqueService/GetCompteRequest", output = "http://ws.enset.ma/BanqueService/GetCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

}
